Make URL parsing for FetchurlProvenance more lenient
Fixes

   error: 'https://cdn.skypack.dev/big.js@^5.2.2' is not a valid URL: leftover

in flake-regressions.